beans:
  -
    name: Garbanzo
    count: 200
    desc: "Versatile bean falafel, hummus and much more description and more."
  -
    name: Baby Lima
    count: 200
    desc: nice white bean
  -
    name: Fava
    count: 49
    desc: broad bean green or cooked
bucket: 50
nprizes: 4
prize:
  - $50 Gift Certificate at the Co-op
  - $30 Gift Certificate at Trader Joe's
  - Cool Beans cookbook
  - The Great Vegan Bean Book cookbook
